# path to the makefile file that should be ran, relative to this file, or an absolute path
mkfile_path : ../examples/premier/Makefile
# target to be ran in the makefile
mk_target : all

# path to files contained in the makefile's folder that should be uploaded
included_files :
  -README
master_ip : 127.0.0.1
distributed_run : yes

# hosts the makefile should be distributed to
hosts :
  - host1 :
      domain : h1.domain.net
      remote_location : ~/test/
      login : hadware
      password : louispd
  - host2:
      domain : h2.domain.net
      login : loulou
      key : .ssh/id_rsa
  - host3:
      domain : h3.domain.net
      remote_location : ~/test/
      login : loulou
      key : .ssh/id_rsa
