# path to the makefile file that should be ran
mkfile_path : ../examples/premier/Makefile
# target to be ran
mk_target : list.txt

# path to files contained in the makefile's folder that should be uploaded
included_files :
  - premier

distributed_run : yes

master_ip : 172.16.18.1

# hosts the makefile should be distributed to
hosts :
  - host1 :
      domain : 172.16.18.131
      remote_location : lm1/
      login : lm1 #lm1
      password : test
  - host2 :
      domain : 172.16.18.132
      remote_location : ubuntu1/
      login : ubuntu1
      password : test
