# path to the makefile file that should be ran
mkfile_path : ../examples/premier/Makefile
# target to be ran
mk_target : list.txt

# path to files contained in the makefile's folder that should be uploaded
included_files :

distributed_run : yes

# hosts the makefile should be distributed to
hosts :
  - host1 :
      domain : localhost
      remote_location : test1/
      login : louis
      password : yU4j123Db
  - host2 :
      domain : localhost
      remote_location : test2/
      login : louis
      password : yU4j123Db
  - host3 :
      domain : localhost
      remote_location : test3/
      login : louis
      password : yU4j123Db